[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clerk-backend-api>=3.0.3",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "motor>=3.7.1",
    "openai>=1.86.0",
    "uvicorn>=0.34.3",
]
